#!/bin/bash


SHECAN_DNS="# Shecan dns server
nameserver 178.22.122.100
nameserver 185.51.200.2"

function show_usage() {
  echo -e "
╭━━━┳╮╱╱╱╱╱╱╱╱╱╱╱╱╱╭━╮╭━╮
┃╭━╮┃┃╱╱╱╱╱╱╱╱╱╱╱╱╱┃┃╰╯┃┃
┃╰━━┫╰━┳━━┳━━┳━━┳━╮┃╭╮╭╮┣━━┳━╮
╰━━╮┃╭╮┃┃━┫╭━┫╭╮┃╭╮┫┃┃┃┃┃╭╮┃╭╮╮
┃╰━╯┃┃┃┃┃━┫╰━┫╭╮┃┃┃┃┃┃┃┃┃╭╮┃┃┃┃
╰━━━┻╯╰┻━━┻━━┻╯╰┻╯╰┻╯╰╯╰┻╯╰┻╯╰╯

shecanman lets you swtich your DNS temporarily.

Usage: shecan [command]

Commands:
on    \t  Switch on Shecan DNS configs
  > shecan on
  
off   \t  Switch off Shecan DNS configs
  > shecan off

status   \t  Show Shecan DNS status
  > shecan status

help  \t  Show this help
  > shecan help"
}

function is_shecan_on() {
  if [[ $(</etc/resolv.conf) != "$SHECAN_DNS" ]]; then
    return 1
  else
    return 0
  fi
}

function switch_on() {
  if is_shecan_on; then
    echo "Shecan is already in use"
  else
    cp /etc/resolv.conf /etc/resolv.conf.backup
    echo "$SHECAN_DNS" >/etc/resolv.conf
    echo "Shecan DNS switched on."
  fi
}

function switch_off() {
  if ! is_shecan_on; then
    echo "Shecan not in use"
  else
    cp /etc/resolv.conf.backup /etc/resolv.conf
    rm /etc/resolv.conf.backup
    echo "Shecan DNS switched off."
  fi
}

function show_status() {
  if is_shecan_on; then
    echo "Shecan is in use."
  else
    echo "Shecan is not in use."
  fi
}

function main() {
  case "$1" in
  "on") switch_on ;;
  "off") switch_off ;;
  "status") show_status ;;
  *) show_usage ;;
  esac
}

if [[ $EUID -ne 0 ]]; then
  echo "Permission denied. Please run as root."
  exit 1
fi

main "$@"
