#!/bin/bash

function show_usage() {
  echo -e "shecan-switch lets you swtich your DNS temporarily.
Usage: shecan [command]
Commands:
on    \t  Switch on Shecan DNS configs
  > shecan on
off   \t  Switch off Shecan DNS configs
  > shecan off
status   \t  Show Shecan DNS status
  > shecan status
help  \t  Show this help
  > shecan help
"
}

SHECAN_DNS="# Shecan dns server
nameserver 178.22.122.100
nameserver 185.51.200.2"

function get_status() {
  if [[ $(</etc/resolv.conf) != "$SHECAN_DNS" ]]; then
    return 1
  else
    return 0
  fi
}

function switch_on() {
  if get_status; then
    echo "Shecan is already in use"
  else
    cp /etc/resolv.conf /etc/resolv.conf.backup
    echo "$SHECAN_DNS" >resolv111.conf
  fi
}

function switch_off() {
  # Todo not implemented
  exit 1
}

function show_status() {
  if get_status; then
    echo "Shecan is in use."
  else
    echo "Shecan is not in use."
  fi
}

function main() {
  case "$1" in
  "on") switch_on ;;
  "off") switch_off ;;
  "status") show_status ;;
  *) show_usage ;;
  esac
}

if [[ $EUID -ne 0 ]]; then
  echo "Permission denied. Please run as root."
  exit 1
fi

main "$@"
