#!/bin/bash

function show_usage() {
  echo -e "shecan-switch lets you swtich your DNS temporarily.
Usage: shecan [command]
Commands:
on    \t  Switch on Shecan DNS configs
  > shecan on
off   \t  Switch off Shecan DNS configs
  > shecan off
status   \t  Show Shecan DNS status
  > shecan status
help  \t  Show this help
  > shecan help
"
}

function switch_on() {
  # Todo not implemneted
  exit 1
}

function switch_off() {
  # Todo not implemented
  exit 1
}

function show_status() {
  # Todo not implemented
  exit 1
}

function main() {
  case "$1" in
  "on") switch_on ;;
  "off") switch_off ;;
  "status") show_status ;;
  *) show_usage ;;
  esac
}

if [[ $EUID -ne 0 ]]; then
  echo "Permission denied. Please run as root."
  exit 1
fi

main "$@"
